from models import Activity

MOCK_ACTIVITIES = [
    Activity(
        name="Eiffel Tower Visit",
        cost=30.0,
        duration_hours=3.0,
        tags=["Sightseeing", "Landmark"],
        description="Visit the iconic Eiffel Tower and enjoy the view.",
        image_url="https://image.pollinations.ai/prompt/Eiffel%20Tower%20Paris%20aesthetic?width=800&height=600&nologo=true",
    ),
    Activity(
        name="Louvre Museum",
        cost=20.0,
        duration_hours=4.0,
        tags=["Art", "Museum"],
        description="See the Mona Lisa and thousands of other works of art.",
        image_url="https://image.pollinations.ai/prompt/Louvre%20Museum%20Paris%20aesthetic?width=800&height=600&nologo=true",
    ),
    Activity(
        name="Seine River Cruise",
        cost=15.0,
        duration_hours=1.5,
        tags=["Relaxing", "Sightseeing"],
        description="A relaxing boat ride along the Seine river.",
        image_url="https://image.pollinations.ai/prompt/Seine%20River%20Cruise%20Paris%20aesthetic?width=800&height=600&nologo=true",
    ),
    Activity(
        name="Montmartre Walking Tour",
        cost=0.0,
        duration_hours=2.0,
        tags=["Walking", "History"],
        description="Explore the historic Montmartre district.",
        image_url="https://image.pollinations.ai/prompt/Montmartre%20Paris%20aesthetic?width=800&height=600&nologo=true",
    ),
    Activity(
        name="Fancy French Dinner",
        cost=80.0,
        duration_hours=2.5,
        tags=["Food", "Luxury"],
        description="A 3-course meal at a Michelin-rated restaurant.",
        image_url="https://image.pollinations.ai/prompt/French%20Dinner%20Paris%20aesthetic?width=800&height=600&nologo=true",
    ),
    Activity(
        name="Street Crêpes",
        cost=5.0,
        duration_hours=0.5,
        tags=["Food", "Budget"],
        description="Delicious sweet or savory crêpes from a street vendor.",
        image_url="https://image.pollinations.ai/prompt/French%20Crepes%20Paris%20aesthetic?width=800&height=600&nologo=true",
    ),
    Activity(
        name="Versailles Palace",
        cost=25.0,
        duration_hours=5.0,
        tags=["History", "Landmark"],
        description="Visit the opulent Palace of Versailles just outside Paris.",
        image_url="https://image.pollinations.ai/prompt/Versailles%20Palace%20Paris%20aesthetic?width=800&height=600&nologo=true",
    ),
    Activity(
        name="Local Park Picnic",
        cost=10.0,
        duration_hours=2.0,
        tags=["Relaxing", "Budget"],
        description="Buy some bread and cheese and relax in the park.",
        image_url="https://image.pollinations.ai/prompt/Paris%20Picnic%20aesthetic?width=800&height=600&nologo=true",
    ),
]
